import {
  ChartPie,
  Wallet,
  Landmark,
  ShoppingBag,
  ShoppingCart,
  FileText,
  Warehouse,
  Wrench,
  CarFront,
  Users,
  Tags,
  BookOpen,
  NotebookPen,
  ChartNoAxesCombined,
  List,
  ListChecks,
  PlugZap,
  ChartSpline,
} from "lucide-react";
export const referenceNav = [
  { id: "overview", label: "Tổng quan", icon: ChartPie },
  { id: "invoices", label: "Quản lý hóa đơn", icon: FileText },
  { id: "cash", label: "Tiền mặt", icon: Wallet },
  { id: "bank", label: "Tiền gửi", icon: Landmark },
  { id: "purchases", label: "Mua hàng", icon: ShoppingBag },
  { id: "sales", label: "Bán hàng", icon: ShoppingCart },
  { id: "inventory", label: "Kho", icon: Warehouse },
  { id: "tools", label: "Công cụ dụng cụ", icon: Wrench },
  { id: "assets", label: "Tài sản cố định", icon: CarFront },
  { id: "payroll", label: "Tiền lương", icon: Users },
  { id: "tax", label: "Thuế", icon: Landmark },
  { id: "cost", label: "Giá thành", icon: Tags },
  { id: "ledger", label: "Tổng hợp", icon: BookOpen },
  { id: "budget", label: "Ngân sách", icon: NotebookPen },
  { id: "analysis", label: "Phân tích tài chính", icon: ChartSpline },
  { id: "reports", label: "Báo cáo", icon: ChartNoAxesCombined },
  { id: "directory", label: "Danh mục", icon: List },
  { id: "opening", label: "Số dư ban đầu", icon: ListChecks },
  { id: "connections", label: "Kết nối vay vốn", icon: PlugZap },
];
export const referenceTabs: Record<string, [string, string][]> = {
  overview: [
    ["overview", "Tổng quan"],
    ["news", "Tính năng mới"],
  ],
  cash: [
    ["process", "Quy trình"],
    ["transactions", "Thu, chi tiền"],
    ["inventory", "Kiểm kê"],
    ["cashflow", "Dự báo dòng tiền"],
    ["reports", "Báo cáo"],
  ],
  bank: [
    ["process", "Quy trình"],
    ["transactions", "Thu, chi tiền"],
    ["reconciliation", "Đối chiếu ngân hàng"],
    ["cashflow", "Dự báo dòng tiền"],
    ["ebanking", "Ngân hàng điện tử"],
    ["borrowings", "Khế ước đi vay"],
    ["loans", "Khế ước cho vay"],
    ["reports", "Báo cáo"],
  ],
  purchases: [
    ["process", "Quy trình"],
    ["chart", "Biểu đồ"],
    ["orders", "Đơn mua hàng"],
    ["contracts", "Hợp đồng mua hàng"],
    ["transactions", "Mua hàng"],
    ["invoices", "Nhận hóa đơn"],
    ["invoice-processing", "Xử lý hóa đơn đầu vào"],
    ["returns", "Trả lại hàng mua"],
    ["discounts", "Giảm giá hàng mua"],
    ["payments", "Trả tiền theo hóa đơn"],
  ],
  sales: [
    ["process", "Quy trình"],
    ["chart", "Biểu đồ"],
    ["quotes", "Báo giá"],
    ["orders", "Đơn đặt hàng"],
    ["contracts", "Hợp đồng bán hàng"],
    ["transactions", "Bán hàng"],
    ["invoices", "Hóa đơn"],
    ["auto-posting", "Tự động hạch toán hóa đơn"],
    ["returns", "Trả lại hàng bán"],
    ["discounts", "Giảm giá hàng bán"],
    ["deferred-revenue", "Phân bổ doanh thu nhận trước"],
    ["receivables", "Công nợ"],
    ["collections", "Thu nợ"],
    ["other", "Khác"],
    ["reports", "Báo cáo"],
  ],
  invoices: [
    ["outgoing", "Hóa đơn đầu ra"],
    ["incoming", "Hóa đơn đầu vào"],
    ["pending", "Hóa đơn cần xử lý"],
    ["errors", "Sai sót, điều chỉnh"],
    ["issuance", "Trạng thái phát hành"],
    ["lookup", "Tra cứu"],
  ],
  inventory: [
    ["process", "Quy trình"],
    ["chart", "Biểu đồ"],
    ["receipts", "Nhập kho"],
    ["issues", "Xuất kho"],
    ["transfers", "Chuyển kho"],
    ["production-orders", "Lệnh sản xuất"],
    ["assembly", "Lắp ráp, tháo dỡ"],
    ["stocktake", "Kiểm kê"],
    ["reports", "Báo cáo"],
    ["items", "Hàng hóa, dịch vụ"],
  ],
  tools: [
    ["process", "Quy trình"],
    ["register", "Sổ theo dõi CCDC"],
    ["increase", "Ghi tăng"],
    ["allocation", "Phân bổ"],
    ["transfer", "Điều chuyển"],
    ["adjustment", "Điều chỉnh"],
    ["decrease", "Ghi giảm"],
    ["stocktake", "Kiểm kê"],
    ["prepaid", "Chi phí trả trước"],
    ["reports", "Báo cáo"],
  ],
  assets: [
    ["process", "Quy trình"],
    ["register", "Sổ tài sản"],
    ["increase", "Ghi tăng"],
    ["depreciation", "Tính khấu hao"],
    ["adjustment", "Điều chỉnh, đánh giá lại"],
    ["transfer", "Điều chuyển"],
    ["decrease", "Ghi giảm"],
    ["stocktake", "Kiểm kê"],
    ["reports", "Báo cáo"],
  ],
  payroll: [
    ["process", "Quy trình"],
    ["attendance", "Chấm công"],
    ["attendance-summary", "Tổng hợp chấm công"],
    ["calculation", "Tính lương"],
    ["posting", "Hạch toán chi phí"],
    ["payment", "Trả lương"],
    ["insurance", "Nộp bảo hiểm"],
    ["reports", "Báo cáo"],
  ],
  tax: [
    ["declarations", "Khai thuế"],
    ["vat", "Thuế GTGT"],
    ["cit", "Thuế TNDN"],
    ["pit", "Thuế TNCN"],
    ["other", "Các loại thuế khác"],
    ["submission", "Nộp, xuất hồ sơ"],
    ["reconciliation", "Đối chiếu thuế"],
    ["reports", "Báo cáo thuế"],
  ],
  cost: [
    ["process", "Quy trình"],
    ["continuous", "Sản xuất liên tục"],
    ["projects", "Công trình"],
    ["orders", "Đơn hàng"],
    ["contracts", "Hợp đồng"],
    ["reports", "Báo cáo"],
  ],
  ledger: [
    ["process", "Quy trình"],
    ["transactions", "Chứng từ nghiệp vụ khác"],
    ["recurring", "Bút toán định kỳ"],
    ["allocation", "Phân bổ"],
    ["closing-entry", "Kết chuyển"],
    ["currency", "Đánh giá ngoại tệ"],
    ["period-close", "Khóa sổ"],
    ["statements", "Lập báo cáo tài chính"],
  ],
  budget: [
    ["overview", "Tổng quan ngân sách"],
    ["planning", "Lập ngân sách"],
    ["approval", "Phê duyệt"],
    ["execution", "Thực hiện ngân sách"],
    ["variance", "Phân tích chênh lệch"],
    ["reports", "Báo cáo"],
  ],
  analysis: [
    ["overview", "Tổng quan tài chính"],
    ["profitability", "Doanh thu và lợi nhuận"],
    ["cashflow", "Dòng tiền"],
    ["working-capital", "Vốn lưu động"],
    ["ratios", "Chỉ số tài chính"],
    ["forecast", "Dự báo"],
  ],
  reports: [
    ["library", "Thư viện báo cáo"],
    ["favorites", "Đã ghim"],
    ["recent", "Gần đây"],
    ["templates", "Mẫu của tôi"],
  ],
  directory: [
    ["partners", "Đối tượng"],
    ["items", "Hàng hóa, dịch vụ"],
    ["organization", "Tổ chức"],
    ["accounting", "Danh mục kế toán"],
  ],
  opening: [
    ["accounts", "Số dư tài khoản"],
    ["receivables", "Công nợ phải thu"],
    ["payables", "Công nợ phải trả"],
    ["inventory", "Tồn kho"],
    ["assets", "Tài sản & CCDC"],
  ],
  connections: [
    ["overview", "Tổng quan vay vốn"],
    ["applications", "Hồ sơ vay"],
    ["offers", "Đề nghị tài trợ"],
    ["contracts", "Khoản vay"],
    ["repayment", "Lịch trả nợ"],
  ],
};
export const reportNames: Record<string, string[]> = {
  cash: [
    "Bảng kê số dư tiền theo ngày",
    "Dòng tiền",
    "S03a1-DNN: Sổ nhật ký thu tiền",
    "Sổ kế toán chi tiết quỹ tiền mặt",
    "S03a2-DNN: Sổ nhật ký chi tiền",
  ],
  bank: [
    "Bảng kê chứng từ theo khế ước cho vay",
    "Bảng kê chứng từ theo khế ước vay",
    "Bảng kê số dư ngân hàng",
    "Bảng kê số dư tiền theo ngày",
    "Báo cáo tổng hợp tình hình khế ước cho vay",
  ],
  purchases: [
    "Sổ chi tiết mua hàng",
    "Chi tiết công nợ phải trả nhà cung cấp",
    "Tổng hợp mua hàng theo mặt hàng",
    "Tổng hợp công nợ phải trả nhà cung cấp",
    "Biên bản đối chiếu và xác nhận công nợ phải trả",
  ],
  sales: [
    "Sổ chi tiết bán hàng",
    "Chi tiết công nợ phải thu khách hàng",
    "Tổng hợp bán hàng theo mặt hàng",
    "Tổng hợp công nợ phải thu khách hàng",
    "Báo cáo chi tiết lãi lỗ theo đơn hàng",
  ],
};
export const settingsGroups = [
  { title: "Nghiệp vụ", items: ["Quản lý danh mục", "Nhập số dư ban đầu"] },
  {
    title: "Tiện ích",
    items: [
      "Bảo trì dữ liệu",
      "Ghi sổ/Bỏ ghi theo lô",
      "Đánh lại số chứng từ",
      "Phục hồi chứng từ đã xóa nhầm",
      "Lấy chứng từ từ dữ liệu khác",
      "Kiểm tra đối chiếu chứng từ, sổ sách",
      "Kiểm soát hồ sơ và hạch toán",
      "Gợi ý, nhắc nhở thông minh",
      "Tra cứu thông tin doanh nghiệp",
      "Nhật ký truy cập",
      "Mã QR thanh toán",
    ],
  },
  {
    title: "Công cụ khác",
    items: [
      "Hướng dẫn chuyển đổi từ SME",
      "Chuyển đổi từ AMIS Kế toán bản cũ",
      "Danh sách lệnh tính giá, bảo trì… đang thực hiện",
      "Cập nhật số dư dữ liệu năm trước",
      "Danh sách người dùng đang truy cập",
    ],
  },
  {
    title: "Công ty của bạn",
    items: [
      "Thông tin công ty",
      "Quản lý người dùng và phân quyền",
      "Quản lý dữ liệu",
    ],
  },
  {
    title: "Thiết lập",
    items: [
      "Tùy chọn",
      "Ngày hạch toán",
      "Kết nối ứng dụng",
      "Ngôn ngữ",
      "Thiết lập cấu hình gửi email",
      "Thiết lập ký số",
      "Thiết lập màu sắc và hiển thị",
    ],
  },
];
