import {
  ChartPie,
  Wallet,
  Landmark,
  ShoppingBag,
  ShoppingCart,
  FileText,
  Warehouse,
  Wrench,
  CarFront,
  Tags,
  BookOpen,
  NotebookPen,
  ChartNoAxesCombined,
  List,
  ListChecks,
  PlugZap,
  ChartSpline,
  CircleDollarSign,
  TicketPercent,
  ShieldCheck,
} from "lucide-react";
export const referenceNav = [
  { id: "overview", label: "Tổng quan", icon: ChartPie },
  { id: "invoices", label: "Quản lý hóa đơn", icon: FileText },
  { id: "cash", label: "Tiền mặt", icon: Wallet },
  { id: "bank", label: "Tiền gửi", icon: Landmark },
  { id: "purchases", label: "Mua hàng", icon: ShoppingBag },
  { id: "sales", label: "Bán hàng", icon: ShoppingCart },
  { id: "inventory", label: "Kho", icon: Warehouse },
  { id: "tools", label: "Công cụ dụng cụ", icon: Wrench },
  { id: "assets", label: "Tài sản cố định", icon: CarFront },
  { id: "payroll", label: "Tiền lương", icon: CircleDollarSign },
  { id: "tax", label: "Thuế", icon: TicketPercent },
  { id: "cost", label: "Giá thành", icon: Tags },
  { id: "insurance", label: "Kết nối bảo hiểm", icon: ShieldCheck, badge: "Mới" },
  { id: "ledger", label: "Tổng hợp", icon: BookOpen },
  { id: "budget", label: "Ngân sách", icon: NotebookPen },
  { id: "reports", label: "Báo cáo", icon: ChartNoAxesCombined },
  { id: "analysis", label: "Phân tích tài chính", icon: ChartSpline },
  { id: "directory", label: "Danh mục", icon: List },
  { id: "opening", label: "Số dư ban đầu", icon: ListChecks },
  { id: "connections", label: "Kết nối vay vốn", icon: PlugZap },
];
const previousReferenceTabs: Record<string, [string, string][]> = {
  overview: [
    ["overview", "Tổng quan"],
    ["news", "Tính năng mới"],
  ],
  cash: [
    ["process", "Quy trình"],
    ["payment-requests", "Đề nghị chi tiền"],
    ["transactions", "Thu, chi tiền"],
    ["advance-settlement", "Đề nghị quyết toán tạm ứng"],
    ["inventory", "Kiểm kê"],
    ["cashflow", "Dự báo dòng tiền"],
    ["reports", "Báo cáo"],
  ],
  bank: [
    ["process", "Quy trình"],
    ["payment-requests", "Đề nghị chi tiền"],
    ["transactions", "Thu, chi tiền"],
    ["advance-settlement", "Đề nghị quyết toán tạm ứng"],
    ["reconciliation", "Đối chiếu ngân hàng"],
    ["cashflow", "Dự báo dòng tiền"],
    ["ebanking", "Ngân hàng điện tử"],
    ["loans", "Khế ước cho vay"],
    ["borrowings", "Khế ước đi vay"],
    ["reports", "Báo cáo"],
  ],
  purchases: [
    ["process", "Quy trình"],
    ["chart", "Biểu đồ"],
    ["orders", "Đơn mua hàng"],
    ["contracts", "Hợp đồng mua hàng"],
    ["transactions", "Mua hàng"],
    ["invoices", "Nhận hóa đơn"],
    ["returns", "Trả lại hàng mua"],
    ["discounts", "Giảm giá hàng mua"],
    ["invoice-processing", "Xử lý hóa đơn đầu vào"],
    ["inventory-items", "Hàng hóa, dịch vụ"],
    ["reconciliation", "Đối chiếu công nợ"],
    ["reports", "Báo cáo"],
  ],
  sales: [
    ["process", "Quy trình"],
    ["chart", "Biểu đồ"],
    ["quotes", "Báo giá"],
    ["orders", "Đơn đặt hàng"],
    ["contracts", "Hợp đồng bán hàng"],
    ["transactions", "Bán hàng"],
    ["invoices", "Hóa đơn"],
    ["auto-posting", "Tự động hạch toán HĐ"],
    ["returns", "Trả lại hàng bán"],
    ["discounts", "Giảm giá hàng bán"],
    ["reports", "Báo cáo"],
    ["receivables", "Công nợ"],
    ["reconciliation", "Đối chiếu công nợ"],
    ["inventory-items", "Hàng hóa, dịch vụ"],
    ["customers", "Khách hàng"],
  ],
  invoices: [
    ["outgoing", "Hóa đơn đầu ra"],
    ["incoming", "Hóa đơn đầu vào"],
    ["pending", "Hóa đơn cần xử lý"],
    ["errors", "Sai sót, điều chỉnh"],
    ["issuance", "Trạng thái phát hành"],
    ["lookup", "Tra cứu"],
  ],
  inventory: [
    ["process", "Quy trình"],
    ["chart", "Biểu đồ"],
    ["receipts", "Nhập kho"],
    ["issues", "Xuất kho"],
    ["transfers", "Chuyển kho"],
    ["production-orders", "Lệnh sản xuất"],
    ["assembly", "Lắp ráp, tháo dỡ"],
    ["stocktake", "Kiểm kê"],
    ["reports", "Báo cáo"],
    ["items", "Hàng hóa, dịch vụ"],
  ],
  tools: [
    ["process", "Quy trình"],
    ["register", "Sổ theo dõi CCDC"],
    ["increase", "Ghi tăng"],
    ["allocation", "Phân bổ"],
    ["transfer", "Điều chuyển"],
    ["adjustment", "Điều chỉnh"],
    ["decrease", "Ghi giảm"],
    ["stocktake", "Kiểm kê"],
    ["prepaid", "Chi phí trả trước"],
    ["reports", "Báo cáo"],
  ],
  assets: [
    ["process", "Quy trình"],
    ["register", "Sổ tài sản"],
    ["increase", "Ghi tăng"],
    ["depreciation", "Tính khấu hao"],
    ["revaluation", "Đánh giá lại"],
    ["transfer", "Điều chuyển"],
    ["decrease", "Ghi giảm"],
    ["stocktake", "Kiểm kê"],
    ["reports", "Báo cáo"],
  ],
  payroll: [
    ["process", "Quy trình"],
    ["attendance", "Chấm công"],
    ["attendance-summary", "Tổng hợp chấm công"],
    ["calculation", "Tính lương"],
    ["posting", "Hạch toán chi phí"],
    ["tax-deduction", "Khấu trừ thuế TNCN"],
    ["reports", "Báo cáo"],
  ],
  tax: [
    ["declarations", "Khai thuế"],
    ["payment-orders", "Giấy nộp tiền"],
    ["risk-suppliers", "Danh sách NCC có rủi ro"],
    ["reports", "Báo cáo"],
  ],
  cost: [
    ["process", "Quy trình"],
    ["continuous-simple", "Sản xuất liên tục - Giản đơn"],
    ["continuous-coefficient", "Sản xuất liên tục - Hệ số, tỷ lệ"],
    ["continuous-step", "Sản xuất liên tục - Phân bước"],
    ["projects", "Công trình"],
    ["orders", "Đơn hàng"],
    ["contracts", "Hợp đồng"],
    ["reports", "Báo cáo"],
  ],
  insurance: [
    ["process", "Quy trình"],
    ["declarations", "Hồ sơ bảo hiểm"],
    ["reconciliation", "Đối chiếu số liệu"],
  ],
  ledger: [
    ["process", "Quy trình"],
    ["advance-settlement-request", "Đề nghị quyết toán tạm ứng"],
    ["transactions", "Chứng từ nghiệp vụ khác"],
    ["closing-entry", "Kết chuyển lãi lỗ"],
    ["reports", "Báo cáo"],
    ["statements", "Lập báo cáo tài chính"],
  ],
  budget: [
    ["charts", "Biểu đồ"],
    ["planning", "Kế hoạch ngân sách"],
    ["reports", "Báo cáo"],
  ],
  analysis: [
    ["overview", "Tổng quan tài chính"],
    ["profitability", "Doanh thu và lợi nhuận"],
    ["cashflow", "Dòng tiền"],
    ["working-capital", "Vốn lưu động"],
    ["ratios", "Chỉ số tài chính"],
    ["forecast", "Dự báo"],
  ],
  reports: [
    ["library", "Thư viện báo cáo"],
    ["favorites", "Đã ghim"],
    ["recent", "Gần đây"],
    ["templates", "Mẫu của tôi"],
  ],
  directory: [
    ["partners", "Đối tượng"],
    ["items", "Hàng hóa, dịch vụ"],
    ["organization", "Tổ chức"],
    ["accounting", "Danh mục kế toán"],
  ],
  opening: [
    ["accounts", "Số dư tài khoản"],
    ["receivables", "Công nợ phải thu"],
    ["payables", "Công nợ phải trả"],
    ["inventory", "Tồn kho"],
    ["assets", "Tài sản & CCDC"],
  ],
  connections: [
    ["overview", "Tổng quan vay vốn"],
    ["applications", "Hồ sơ vay"],
    ["offers", "Đề nghị tài trợ"],
    ["contracts", "Khoản vay"],
    ["repayment", "Lịch trả nợ"],
  ],
};

export type ReferenceTabNode = {
  id: string;
  label: string;
  configurable?: boolean;
  children?: ReferenceTabNode[];
  menuLabel?: string;
  screenTitle?: string;
};

const node = (
  id: string,
  label: string,
  children?: ReferenceTabNode[],
  options?: Pick<
    ReferenceTabNode,
    "configurable" | "menuLabel" | "screenTitle"
  >,
): ReferenceTabNode => ({ id, label, children, ...options });

const auditedTabs: Record<string, ReferenceTabNode[]> = {
  cash: [
    node("process", "Quy trình"),
    node("payment-requests", "Đề nghị chi tiền"),
    node("transactions", "Thu, chi tiền"),
    node("advance-settlement", "Đề nghị quyết toán tạm ứng"),
    node("inventory", "Kiểm kê"),
    node("cashflow", "Dự báo dòng tiền"),
    node("reports", "Báo cáo"),
  ],
  bank: [
    node("process", "Quy trình"),
    node("payment-requests", "Đề nghị chi tiền"),
    node("transactions", "Thu, chi tiền"),
    node("advance-settlement", "Đề nghị quyết toán tạm ứng"),
    node("reconciliation", "Đối chiếu ngân hàng"),
    node("cashflow", "Dự báo dòng tiền"),
    node("ebanking", "Ngân hàng điện tử"),
    node("loans", "Khế ước cho vay"),
    node("borrowings", "Khế ước đi vay"),
    node("reports", "Báo cáo"),
  ],
  purchases: [
    node("process", "Quy trình"),
    node("chart", "Biểu đồ", undefined, { configurable: true }),
    node("orders", "Đơn mua hàng"),
    node("contracts", "Hợp đồng mua hàng"),
    node("transactions", "Mua hàng"),
    node("invoices", "Nhận hóa đơn"),
    node("returns", "Trả lại hàng mua"),
    node("discounts", "Giảm giá hàng mua"),
    node("invoice-processing", "Xử lý hóa đơn đầu vào", [
      node("inbox", "Hộp thư hóa đơn & AI OCR"),
      node("supplier-risk", "Kiểm tra rủi ro nhà cung cấp"),
      node("xml-validation", "Kiểm tra tính hợp lệ XML"),
    ]),
    node("inventory-items", "Hàng hóa, dịch vụ"),
    node("reconciliation", "Đối chiếu công nợ"),
    node("reports", "Báo cáo"),
  ],
  sales: [
    node("process", "Quy trình"),
    node("chart", "Biểu đồ", undefined, { configurable: true }),
    node("quotes", "Báo giá"),
    node("orders", "Đơn đặt hàng"),
    node("contracts", "Hợp đồng bán hàng"),
    node("transactions", "Bán hàng"),
    node("invoices", "Hóa đơn"),
    node("auto-posting", "Tự động hạch toán HĐ"),
    node("returns", "Trả lại hàng bán"),
    node("discounts", "Giảm giá hàng bán"),
    node("reports", "Báo cáo"),
    node("receivables", "Công nợ"),
    node("reconciliation", "Đối chiếu công nợ"),
    node("inventory-items", "Hàng hóa, dịch vụ"),
    node("customers", "Khách hàng"),
  ],
  invoices: [
    node("incoming", "Hóa đơn đầu vào", [
      node("inbox", "Hộp thư hóa đơn & AI OCR"),
      node("unprocessed", "Hóa đơn chưa hạch toán"),
      node("processed", "Hóa đơn đã hạch toán"),
    ]),
    node("outgoing", "Hóa đơn đầu ra & Phát hành"),
    node("risk-warning", "Cảnh báo rủi ro hóa đơn", [
      node("supplier-risk", "Nhà cung cấp rủi ro cao về thuế"),
      node("cash-limit", "Cảnh báo chi tiền mặt trong ngày > 5 triệu"),
      node("xml-errors", "Hóa đơn sai thông tin / Chữ ký số lỗi"),
    ]),
    node("adjustments", "Xử lý sai sót, điều chỉnh, thay thế"),
    node("reports", "Báo cáo hóa đơn điện tử"),
  ],
  inventory: [
    node("process", "Quy trình"),
    node("chart", "Biểu đồ", undefined, { configurable: true }),
    node("receipts", "Nhập kho"),
    node("issues", "Xuất kho"),
    node("transfers", "Chuyển kho"),
    node("production-orders", "Lệnh sản xuất"),
    node("assembly", "Lắp ráp, tháo dỡ"),
    node("stocktake", "Kiểm kê"),
    node("reports", "Báo cáo", undefined, { configurable: true }),
    node("items", "Hàng hóa, dịch vụ", undefined, { configurable: true }),
  ],
  tools: [
    node("process", "Quy trình"),
    node("register", "Sổ theo dõi công cụ dụng cụ", [
      node("by-tool", "Theo công cụ dụng cụ", undefined, {
        screenTitle: "Sổ CCDC theo công cụ dụng cụ",
      }),
      node("by-department", "Theo đơn vị sử dụng", undefined, {
        screenTitle: "Sổ CCDC theo đơn vị sử dụng",
      }),
    ]),
    node("management", "Quản lý công cụ dụng cụ", [
      node("increase", "Ghi tăng", undefined, {
        menuLabel: "Ghi tăng CCDC",
        screenTitle: "Ghi tăng CCDC",
      }),
      node("allocation", "Phân bổ chi phí"),
      node("adjustment", "Điều chỉnh"),
      node("transfer", "Điều chuyển"),
      node("decrease", "Ghi giảm"),
      node("stocktake", "Kiểm kê"),
    ]),
    node("prepaid", "Chi phí trả trước", [
      node("list", "Danh sách chi phí trả trước"),
      node("allocation", "Phân bổ chi phí trả trước"),
      node("decrease", "Ghi giảm"),
    ]),
    node("reports", "Báo cáo", [
      node("tools", "Báo cáo CCDC"),
      node("prepaid", "Báo cáo chi phí trả trước"),
      node("reconciliation", "Báo cáo đối chiếu"),
    ]),
  ],
  assets: [
    node("process", "Quy trình"),
    node("register", "Sổ tài sản"),
    node("increase", "Ghi tăng"),
    node("depreciation", "Tính khấu hao"),
    node("revaluation", "Đánh giá lại"),
    node("transfer", "Điều chuyển"),
    node("decrease", "Ghi giảm"),
    node("stocktake", "Kiểm kê"),
    node("reports", "Báo cáo"),
  ],
  payroll: [
    node("process", "Quy trình"),
    node("attendance", "Chấm công"),
    node("attendance-summary", "Tổng hợp chấm công"),
    node("calculation", "Tính lương"),
    node("posting", "Hạch toán chi phí"),
    node("tax-deduction", "Khấu trừ thuế TNCN"),
    node("reports", "Báo cáo"),
  ],
  tax: [
    node("declarations", "Khai thuế"),
    node("payment-orders", "Giấy nộp tiền"),
    node("risk-suppliers", "Danh sách NCC có rủi ro"),
    node("reports", "Báo cáo"),
  ],
  cost: [
    node("process", "Quy trình"),
    node("continuous-simple", "Sản xuất liên tục - Giản đơn"),
    node("continuous-coefficient", "Sản xuất liên tục - Hệ số, tỷ lệ"),
    node("continuous-step", "Sản xuất liên tục - Phân bước"),
    node("projects", "Công trình"),
    node("orders", "Đơn hàng"),
    node("contracts", "Hợp đồng"),
    node("reports", "Báo cáo"),
  ],
  insurance: [
    node("process", "Quy trình"),
    node("declarations", "Hồ sơ bảo hiểm"),
    node("reconciliation", "Đối chiếu số liệu"),
  ],
  ledger: [
    node("process", "Quy trình"),
    node("advance-settlement-request", "Đề nghị quyết toán tạm ứng"),
    node("transactions", "Chứng từ nghiệp vụ khác"),
    node("closing-entry", "Kết chuyển lãi lỗ"),
    node("statements", "Lập báo cáo tài chính"),
    node("reports", "Báo cáo"),
  ],
  budget: [
    node("charts", "Biểu đồ"),
    node("planning", "Kế hoạch ngân sách"),
    node("reports", "Báo cáo"),
  ],
  analysis: [
    node("ratios", "Chỉ số tài chính"),
    node("reports", "Báo cáo phân tích"),
  ],
};

export const referenceTabHierarchy: Record<string, ReferenceTabNode[]> = {
  ...Object.fromEntries(
    Object.entries(previousReferenceTabs).map(([moduleId, tabs]) => [
      moduleId,
      tabs.map(([id, label]) => node(id, label)),
    ]),
  ),
  ...auditedTabs,
};

export const referenceTabs: Record<string, [string, string][]> =
  Object.fromEntries(
    Object.entries(referenceTabHierarchy).map(([moduleId, tabs]) => [
      moduleId,
      tabs.map(({ id, label }) => [id, label]),
    ]),
  );
export const reportNames: Record<string, string[]> = {
  cash: [
    "Bảng kê số dư tiền theo ngày",
    "Dòng tiền",
    "S03a1 - DN: Sổ nhật ký thu tiền",
    "Sổ kế toán chi tiết quỹ tiền mặt",
    "S03a2 - DN: Sổ nhật ký chi tiền",
  ],
  bank: [
    "Bảng kê chứng từ theo khế ước cho vay",
    "Bảng kê chứng từ theo khế ước vay",
    "Bảng kê số dư ngân hàng",
    "Bảng kê số dư tiền theo ngày",
    "Báo cáo tổng hợp tình hình khế ước cho vay",
  ],
  purchases: [
    "Sổ chi tiết mua hàng",
    "Chi tiết công nợ phải trả nhà cung cấp",
    "Tổng hợp mua hàng theo mặt hàng",
    "Tổng hợp công nợ phải trả nhà cung cấp",
    "Biên bản đối chiếu và xác nhận công nợ phải trả",
  ],
  sales: [
    "Sổ chi tiết bán hàng",
    "Chi tiết công nợ phải thu khách hàng",
    "Tổng hợp bán hàng theo mặt hàng",
    "Tổng hợp công nợ phải thu khách hàng",
    "Báo cáo chi tiết lãi lỗ theo đơn hàng",
  ],
  ledger: [
    "Sổ chi tiết các tài khoản",
    "Sổ nhật ký chung",
    "Tổng hợp công nợ nhân viên",
    "Tổng hợp công nợ theo đối tượng",
    "B01a-DN: Báo cáo tình hình tài chính giữa niên độ (Dạng đầy đủ)",
  ],
  budget: [
    "Kế hoạch ngân sách",
    "Tình hình thực hiện ngân sách",
    "Tình hình thực hiện doanh thu so với kế hoạch",
    "Tình hình chi phí thực tế so với kế hoạch",
  ],
};
export const settingsGroups = [
  { title: "Nghiệp vụ", items: ["Quản lý danh mục", "Nhập số dư ban đầu"] },
  {
    title: "Tiện ích",
    items: [
      "Bảo trì dữ liệu",
      "Ghi sổ/Bỏ ghi theo lô",
      "Đánh lại số chứng từ",
      "Phục hồi chứng từ đã xóa nhầm",
      "Lấy chứng từ từ dữ liệu khác",
      "Kiểm tra đối chiếu chứng từ, sổ sách",
      "Kiểm tra & cảnh báo nhà cung cấp rủi ro thuế",
      "Đối chiếu hóa đơn với dữ liệu Tổng cục Thuế",
      "Kiểm soát hồ sơ và hạch toán",
      "Trợ lý AI MISA AVA: Cấu hình gợi ý hạch toán",
      "Gợi ý, nhắc nhở thông minh",
      "Tra cứu thông tin doanh nghiệp",
      "Nhật ký truy cập",
      "Mã QR thanh toán",
    ],
  },
  {
    title: "Công cụ khác",
    items: [
      "Chuyển đổi dữ liệu sang Thông tư 99/2025/TT-BTC",
      "Hướng dẫn chuyển đổi từ SME",
      "Chuyển đổi từ AMIS Kế toán bản cũ",
      "Danh sách lệnh tính giá, bảo trì… đang thực hiện",
      "Cập nhật số dư dữ liệu năm trước",
      "Danh sách người dùng đang truy cập",
    ],
  },
  {
    title: "Công ty của bạn",
    items: [
      "Thông tin công ty",
      "Quản lý người dùng và phân quyền",
      "Quản lý dữ liệu",
    ],
  },
  {
    title: "Thiết lập",
    items: [
      "Tùy chọn",
      "Ngày hạch toán",
      "Kết nối ứng dụng",
      "Thiết lập kết nối sàn TMĐT (Shopee, TikTok Shop)",
      "Thiết lập kết nối Ngân hàng điện tử (mBank)",
      "Ngôn ngữ",
      "Thiết lập cấu hình gửi email",
      "Thiết lập ký số từ xa (SmartCA / eSign)",
      "Thiết lập màu sắc và hiển thị",
    ],
  },
];
