import {
  Bot,
  ChartPie,
  Wallet,
  Landmark,
  ShoppingBag,
  ShoppingCart,
  FileText,
  Warehouse,
  Wrench,
  CarFront,
  Users,
  Tags,
  BookOpen,
  NotebookPen,
  ChartNoAxesCombined,
  List,
  ListChecks,
  PlugZap,
  SlidersHorizontal,
} from "lucide-react";
export const referenceNav = [
  { id: "assistant", label: "Trợ lý AI", icon: Bot },
  { id: "overview", label: "Tổng quan", icon: ChartPie },
  { id: "cash", label: "Tiền mặt", icon: Wallet },
  { id: "bank", label: "Tiền gửi", icon: Landmark },
  { id: "purchases", label: "Mua hàng", icon: ShoppingBag },
  { id: "sales", label: "Bán hàng", icon: ShoppingCart },
  { id: "invoices", label: "Quản lý hóa đơn", icon: FileText },
  { id: "inventory", label: "Kho", icon: Warehouse },
  { id: "tools", label: "Công cụ dụng cụ", icon: Wrench },
  { id: "assets", label: "Tài sản cố định", icon: CarFront },
  { id: "payroll", label: "Tiền lương", icon: Users },
  { id: "tax", label: "Thuế", icon: Landmark },
  { id: "cost", label: "Giá thành", icon: Tags },
  { id: "ledger", label: "Tổng hợp", icon: BookOpen },
  { id: "budget", label: "Ngân sách", icon: NotebookPen },
  { id: "reports", label: "Báo cáo", icon: ChartNoAxesCombined },
  { id: "analysis", label: "Phân tích tài chính", icon: ChartPie },
  { id: "directory", label: "Danh mục", icon: List },
  { id: "opening", label: "Số dư ban đầu", icon: ListChecks },
  { id: "connections", label: "Giải pháp kết nối", icon: PlugZap },
  { id: "settings", label: "Thiết lập", icon: SlidersHorizontal },
];
export const referenceTabs: Record<string, [string, string][]> = {
  overview: [
    ["overview", "Tổng quan"],
    ["news", "Tính năng mới"],
  ],
  cash: [
    ["process", "Quy trình"],
    ["transactions", "Thu, chi tiền"],
    ["inventory", "Kiểm kê"],
    ["cashflow", "Dự báo dòng tiền"],
    ["reports", "Báo cáo"],
  ],
  bank: [
    ["process", "Quy trình"],
    ["transactions", "Thu, chi tiền"],
    ["cashflow", "Dự báo dòng tiền"],
    ["borrowings", "Khế ước đi vay"],
    ["loans", "Khế ước cho vay"],
    ["reports", "Báo cáo"],
  ],
  purchases: [
    ["process", "Quy trình"],
    ["chart", "Biểu đồ"],
    ["orders", "Đơn mua hàng"],
    ["contracts", "Hợp đồng mua hàng"],
    ["transactions", "Mua hàng"],
    ["invoices", "Nhận hóa đơn"],
    ["returns", "Trả lại hàng mua"],
    ["discounts", "Giảm giá hàng mua"],
    ["payables", "Đối chiếu công nợ"],
    ["other", "Khác"],
  ],
  sales: [
    ["process", "Quy trình"],
    ["chart", "Biểu đồ"],
    ["quotes", "Báo giá"],
    ["orders", "Đơn đặt hàng"],
    ["contracts", "Hợp đồng bán hàng"],
    ["transactions", "Bán hàng"],
    ["invoices", "Hóa đơn"],
    ["returns", "Trả lại hàng bán"],
    ["discounts", "Giảm giá hàng bán"],
    ["receivables", "Công nợ"],
    ["collections", "Thu nợ"],
    ["other", "Khác"],
  ],
};
export const reportNames: Record<string, string[]> = {
  cash: [
    "Bảng kê số dư tiền theo ngày",
    "Dòng tiền",
    "S03a1-DNN: Sổ nhật ký thu tiền",
    "Sổ kế toán chi tiết quỹ tiền mặt",
    "S03a2-DNN: Sổ nhật ký chi tiền",
  ],
  bank: [
    "Bảng kê chứng từ theo khế ước cho vay",
    "Bảng kê chứng từ theo khế ước vay",
    "Bảng kê số dư ngân hàng",
    "Bảng kê số dư tiền theo ngày",
    "Báo cáo tổng hợp tình hình khế ước cho vay",
  ],
  purchases: [
    "Sổ chi tiết mua hàng",
    "Chi tiết công nợ phải trả nhà cung cấp",
    "Tổng hợp mua hàng theo mặt hàng",
    "Tổng hợp công nợ phải trả nhà cung cấp",
    "Biên bản đối chiếu và xác nhận công nợ phải trả",
  ],
  sales: [
    "Sổ chi tiết bán hàng",
    "Chi tiết công nợ phải thu khách hàng",
    "Tổng hợp bán hàng theo mặt hàng",
    "Tổng hợp công nợ phải thu khách hàng",
    "Báo cáo chi tiết lãi lỗ theo đơn hàng",
  ],
};
export const settingsGroups = [
  { title: "Nghiệp vụ", items: ["Quản lý danh mục", "Nhập số dư ban đầu"] },
  {
    title: "Tiện ích",
    items: [
      "Bảo trì dữ liệu",
      "Ghi sổ/Bỏ ghi theo lô",
      "Đánh lại số chứng từ",
      "Phục hồi chứng từ đã xóa nhầm",
      "Lấy chứng từ từ dữ liệu khác",
      "Kiểm tra đối chiếu chứng từ, sổ sách",
      "Kiểm soát hồ sơ và hạch toán",
      "Gợi ý, nhắc nhở thông minh",
      "Tra cứu thông tin doanh nghiệp",
      "Nhật ký truy cập",
      "Mã QR thanh toán",
    ],
  },
  {
    title: "Công cụ khác",
    items: [
      "Hướng dẫn chuyển đổi từ SME",
      "Chuyển đổi từ AMIS Kế toán bản cũ",
      "Danh sách lệnh tính giá, bảo trì… đang thực hiện",
      "Cập nhật số dư dữ liệu năm trước",
      "Danh sách người dùng đang truy cập",
    ],
  },
  {
    title: "Công ty của bạn",
    items: [
      "Thông tin công ty",
      "Quản lý người dùng và phân quyền",
      "Quản lý dữ liệu",
    ],
  },
  {
    title: "Thiết lập",
    items: [
      "Tùy chọn",
      "Ngày hạch toán",
      "Kết nối ứng dụng",
      "Ngôn ngữ",
      "Thiết lập cấu hình gửi email",
      "Thiết lập ký số",
      "Thiết lập màu sắc và hiển thị",
    ],
  },
];
